---
# tasks to change the root password
- name: change the root password
  user:
    name: root
    password: "{{ common_root_password }}"
  when: common_root_password != ''
  tags:
    - common
    - common_root_password

