---
# install tasks for fail2ban

- name: ensure the epel is installed
  yum:
    name: epel-release
    state: present
  tags:
    - common
    - common_fail2ban

- name: ensure fail2ban is installed
  yum:
    name: fail2ban
    state: present
  tags:
    - common
    - common_fail2ban

- name: configure fail2ban
  template:
    src: "{{ common_fail2ban_template }}"
    dest: "{{ common_fail2ban_destination }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban

  tags:
    - common
    - common_fail2ban

- name: ensure fail2ban is running
  service:
    name: fail2ban
    enabled: yes
    state: started
  tags:
    - common
    - common_fail2ban
