---
# handlers file for common
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart iptables
  service:
    name: iptables
    enabled: yes
    state: restarted

- name: restart sshd
  service:
    name: sshd
    enabled: yes
    state: restarted

